### ISSUE TITLE
DDPG: Expected object of device type cuda but got device type cpu for argument #1 'self' in call to _th_addmm

### ISSUE THREAD

**Issue by MeixinZhu** [p-christ/Deep-Reinforcement-Learning-Algorithms-with-PyTorch#33]
(rl) D:\Downloads\Deep-Reinforcement-Learning-Algorithms-with-PyTorch>python results/Mountain_Car.py
AGENT NAME: TD3
?[1m1.1: TD3?[0m
TITLE  MountainCarContinuous
{'Actor': {'learning_rate': 0.003, 'linear_hidden_units': [20, 20], 'final_layer_activation': None, 'batch_norm': False, 'tau': 0.005, 'gradient_clipping_norm': 5, 'initialiser': 'Xavier', 'output_activation': None, 'hidden_activations': 'relu', 'dropout': 0.0,
 'columns_of_data_to_be_embedded': [], 'embedding_dimensions': [], 'y_range': ()}, 'Critic': {'learning_rate': 0.02, 'linear_hidden_units': [20, 20], 'final_layer_activation': None, 'batch_norm': False, 'buffer_size': 1000000, 'tau': 0.005, 'gradient_clipping_n
orm': 5, 'initialiser': 'Xavier', 'output_activation': None, 'hidden_activations': 'relu', 'dropout': 0.0, 'columns_of_data_to_be_embedded': [], 'embedding_dimensions': [], 'y_range': ()}, 'min_steps_before_learning': 1000, 'batch_size': 256, 'discount_rate': 0
.99, 'mu': 0.0, 'theta': 0.15, 'sigma': 0.25, 'action_noise_std': 0.2, 'action_noise_clipping_range': 0.5, 'update_every_n_steps': 20, 'learning_updates_per_learning_session': 10, 'automatically_tune_entropy_hyperparameter': True, 'entropy_term_weight': None, '
add_extra_noise': True, 'do_evaluation_iterations': True, 'clip_rewards': False}
RANDOM SEED  1187266124
Traceback (most recent call last):
  File "results/Mountain_Car.py", line 100, in <module>
    trainer.run_games_for_agents()
  File "D:\Downloads\Deep-Reinforcement-Learning-Algorithms-with-PyTorch\agents\Trainer.py", line 79, in run_games_for_agents
    self.run_games_for_agent(agent_number + 1, agent_class)
  File "D:\Downloads\Deep-Reinforcement-Learning-Algorithms-with-PyTorch\agents\Trainer.py", line 117, in run_games_for_agent
    game_scores, rolling_scores, time_taken = agent.run_n_episodes()
  File "D:\Downloads\Deep-Reinforcement-Learning-Algorithms-with-PyTorch\agents\Base_Agent.py", line 189, in run_n_episodes
    self.step()
  File "D:\Downloads\Deep-Reinforcement-Learning-Algorithms-with-PyTorch\agents\actor_critic_agents\DDPG.py", line 40, in step
    self.critic_learn(states, actions, rewards, next_states, dones)
  File "D:\Downloads\Deep-Reinforcement-Learning-Algorithms-with-PyTorch\agents\actor_critic_agents\TD3.py", line 36, in critic_learn
    critic_targets_next =  self.compute_critic_values_for_next_states(next_states)
  File "D:\Downloads\Deep-Reinforcement-Learning-Algorithms-with-PyTorch\agents\actor_critic_agents\TD3.py", line 27, in compute_critic_values_for_next_states
    actions_next = self.actor_target(next_states)
  File "C:\ProgramData\Anaconda3\envs\rl\lib\site-packages\torch\nn\modules\module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\rl\lib\site-packages\nn_builder\pytorch\NN.py", line 118, in forward
    x = self.process_hidden_layers(x)
  File "C:\ProgramData\Anaconda3\envs\rl\lib\site-packages\nn_builder\pytorch\NN.py", line 153, in process_hidden_layers
    x = self.get_activation(self.hidden_activations, layer_ix)(linear_layer(x))
  File "C:\ProgramData\Anaconda3\envs\rl\lib\site-packages\torch\nn\modules\module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\rl\lib\site-packages\torch\nn\modules\linear.py", line 87, in forward
    return F.linear(input, self.weight, self.bias)
  File "C:\ProgramData\Anaconda3\envs\rl\lib\site-packages\torch\nn\functional.py", line 1370, in linear
    ret = torch.addmm(bias, input, weight.t())
RuntimeError: Expected object of device type cuda but got device type cpu for argument #1 'self' in call to _th_addmm

**Comment by MeixinZhu** [comment]
Seems like the problem is caused by the fact that I am using gpu version of torch. Once I install a cpu version of torch, the algorithm can run with cpu.

**Comment by mmlyj** [comment]
Actually,it's a bug . it's caused by the the line 15 of file Replay_Buffer.py, it would  make the data send to GPU when config.use_GPU=False
