### ISSUE TITLE
Actor output the wrong size in CartPole using PPO

### ISSUE THREAD

**Issue by yaoxunji** [p-christ/Deep-Reinforcement-Learning-Algorithms-with-PyTorch#42]
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "D:\Anaconda\lib\multiprocessing\pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "D:\Anaconda\lib\multiprocessing\pool.py", line 44, in mapstar
    return list(map(*args))
  File "D:\papercode\RL\algorithm\Deep-Reinforcement-Learning-Algorithms-with-PyTorch-master\utilities\Parallel_Experience_Generator.py", line 41, in __call__
    return self.play_1_episode(exploration)
  File "D:\papercode\RL\algorithm\Deep-Reinforcement-Learning-Algorithms-with-PyTorch-master\utilities\Parallel_Experience_Generator.py", line 51, in play_1_episode
    action = self.pick_action(self.policy, state, epsilon_exploration)
  File "D:\papercode\RL\algorithm\Deep-Reinforcement-Learning-Algorithms-with-PyTorch-master\utilities\Parallel_Experience_Generator.py", line 79, in pick_action
    action_distribution = create_actor_distribution(self.action_types, actor_output, self.action_size)
  File "D:\papercode\RL\algorithm\Deep-Reinforcement-Learning-Algorithms-with-PyTorch-master\utilities\Utility_Functions.py", line 28, in create_actor_distribution
    assert actor_output.size()[1] == action_size * 2, "Actor output the wrong size"
AssertionError: Actor output the wrong size

**Comment by shuferhoo** [comment]
take a try to change file "\Deep-Reinforcement-Learning-Algorithms-with-PyTorch-master\utilities\Parallel_Experience_Generator.py", line 19,
self.action_types = "DISCRETE" if self.environment.action_space.dtype **==int** else "CONTINUOUS" 
to 
self.action_types = "DISCRETE" if self.environment.action_space.dtype **in [int, 'int64']** else "CONTINUOUS"
